### PR TITLE
Mozilla Public License Version 2.0

### PR DESCRIPTION
**Pull request by skorfmann**
MPL 2.0 seems to be a good choice for open source projects http://veldstra.org/2016/12/09/you-should-choose-mpl2-for-your-opensource-project.html

Thoughts?

### CODE REVIEW

**Comment by littldr** [comment]
> The practicalities
> It takes just a tiny bit more work to use MPL 2.0. Apart from placing the appropriate LICENSE.txt in the root of your repo, you also need to add the license header to every file that is distributed under it. Mozilla provide license header templates for a variety of commenting syntaxes.

Do we really need to add that Header to all files? Or can we somehow say something like this in the README: 'All files in this repository are licensed under MPL 2.0'?

**Comment by skorfmann** [comment]
Good question, according to the license you can mention it in a separate file. However, I looked at the Terraform repo, and it looks like they don't do headers either.

**Comment by skorfmann** [comment]
Well, perhaps MIT is simpler?

**Comment by littldr** [comment]
Nah, let's stick with MPL 2.0. Maybe we can automate the header stuff if it really gets annoying.

**Pull request merged**
